#!/bin/bash
export LS_OPTIONS="--color=always --group-directories-first"

alias ls="ls $LS_OPTIONS -hF"
alias ll="ls $LS_OPTIONS -lhF"
alias diff="diff --color=auto"
alias c="clear"
alias v="vim"
alias lynx="lynx -vikeys"
alias ~="cd ~ && ls -a"

alias dnd="cd ~/documents/D\&D/"
alias cos="cd ~/documents/D\&D/Curse\ of\ Strahd"
alias m="~/dotfiles/scripts/fuzzymon/monster.sh"

alias pacman="sudo pacman"
alias wifi-menu="sudo wifi-menu"

alias weather="curl http://wttr.in/48197"
alias pythong="echo HAHA THONG RELATED ASCII ART"
