#!/bin/bash
export LS_OPTIONS="--color=always --group-directories-first"

alias ls="gls $LS_OPTIONS -hF"
alias ll="gls $LS_OPTIONS -lhF"
alias c="clear"

alias weather="curl http://wttr.in/48197"
alias passgen="python ~/etc/scripts/passgen.py"
alias colors="python ~/etc/scripts/unowns.py"
alias serve="php -S localhost:8000"
